services:
###> doctrine/doctrine-bundle ###
  database:
    image: "mysql:latest"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "Wikout"
    container_name: "wikoutdatabase"

  symfony:
    image: "axel548/wikout:v1"
    ports:
      - "8088:80"
    container_name: "symfony_wikout"  

  angular:
    image: "axel548/angular_wikout:v1"
    ports:
      - "8085:80"
    container_name: "angular_wikout"