controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

ApiLogin:
    path: /api/login

api_commentaireIndex:
    path: /api/commentaire/index
    controller: App\Controller\CommentairesController::index_api
    methods: GET

api_commentaireDelete:
    path: /api/commentaire/delete/{id}
    controller: App\Controller\CommentairesController::delete_api
    methods: DELETE

api_contactIndex:
    path: /api/contact/index
    controller: App\Controller\ContactController::index_api
    methods: GET

